package org.example.db.dao;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import org.example.db.Dao;
import org.example.db.DaoBase;
import org.example.db.EntityBase;
import org.example.db.HsqlUnitOfWork;
import org.example.pizza.Client;
import org.example.pizza.Pizza;

public class HsqlPizzaDao extends DaoBase<Pizza>  implements Dao<Pizza>{

	
	private Statement stmt;
	private PreparedStatement insert;
	private PreparedStatement delete;
	private PreparedStatement update;
	private PreparedStatement getById;
	private PreparedStatement getAll;
	
	
	public HsqlPizzaDao(HsqlUnitOfWork uow)
	{
		super(uow);
		try {
			Connection connection = uow.getConnection();
			stmt = connection.createStatement();
			
			ResultSet rs = connection.getMetaData().getTables(null, null, null, null);
			
			boolean exists = false;
			while(rs.next())
			{
				if("Pizza".equalsIgnoreCase(rs.getString("TABLE_NAME")))
				{
					exists = true;
					break;
				}
			}
			
			insert = connection.prepareStatement(""
					+ "INSERT INTO Pizza(name,description,prize)"
					+ " VALUES(?,?,?)");
			
			getById = connection.prepareStatement(""
					+ "SELECT * FROM Pizza WHERE id=?");
			
			delete = connection.prepareStatement("DELETE FROM Pizza WHERE id=?");
			
			getAll = connection.prepareStatement("SELECT * FROM Pizza");
			
			update = connection.prepareStatement(""
					+ "update Pizza set"
					+ "(name,description,prize)=(?,?,?)"
					+ "where id=?");
			
			if(!exists)
			{
				stmt.executeUpdate(""
						+ "CREATE TABLE Pizza("
						+ "id bigint GENERATED BY DEFAULT AS IDENTITY,"
						+ "name varchar(50),"
						+ "description varchar(500),"
						+ "prize double,"
						+ ")");
				
			}
		} catch (SQLException e) {
			e.printStackTrace();
		}
		
	}

	@Override
	public void persistAdd(EntityBase entity) {
		
		Pizza ent = (Pizza)entity;
		try {
			insert.setString(1, ent.getName());
			insert.setString(2, ent.getDescription());
			insert.setDouble(3, ent.getPrize());
			insert.executeUpdate();
			
		} catch (SQLException e) {
			e.printStackTrace();
		}
		
	}

	@Override
	public void persistDelete(EntityBase entity) {
		Pizza ent = (Pizza) entity;
		try 
		{
			delete.setInt(1, ent.getId());
			delete.executeUpdate();

		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	@Override
	public List<Pizza> getAll() {
			List<Pizza> clients = new ArrayList<Pizza>();
		
		try
		{
			ResultSet rs = getAll.executeQuery();
			while(rs.next()){
				
				Pizza p = new Pizza();
				p.setId(rs.getInt("id"));
				p.setDescription(rs.getString("description"));
				p.setPrize(rs.getDouble("prize"));
				p.setName(rs.getString("name"));
				clients.add(p);
			}
		}
		
		catch(Exception ex)
		{
			ex.printStackTrace();
		}
		
		return clients;
	}

	@Override
	public Pizza get(int id) {
		Pizza p = null;
		try {
			getById.setInt(1, id);
			ResultSet rs = getById.executeQuery();
			while(rs.next())
			{
				p = new Pizza();
				p.setId(rs.getInt("id"));
				p.setDescription(rs.getString("description"));
				p.setPrize(rs.getDouble("prize"));
				p.setName(rs.getString("name"));
			}
			
		} catch (SQLException e) {
			e.printStackTrace();
		}
		
		return p;
	}

	@Override
	public void persistUpdate(EntityBase entity) {
		Pizza ent = (Pizza) entity;
		try
		{
			update.setString(1, ent.getName());
			update.setString(2, ent.getDescription());
			update.setDouble(3, ent.getPrize());
			update.setInt(5, ent.getId());
			update.executeUpdate();
		}
		catch(Exception ex)
		{
			ex.printStackTrace();
		}
		
	}


	
	
}
